# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac94fef0b787b8db62f33930d350a885073108c00f99983890960121c0e2a27f5f00db993689270baddad3a91678b9a9565ec2e3c39f26746f68170c22999064

test:
  secret_key_base: 713aa82b17e88ed437b6f05f1c856d90e76557599591a979cb30568e8f7bb1de2e2d05b20f0340215b10fd8a58bf2c3c75e759314b33512319bdd4af42367eaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
